const Data = [
    {
        id: 1,
        discount: null,
        imgURL1: 'https://new.axilthemes.com/demo/template/etrade-rtl/assets/images/product/electric/product-04.png',
        imgURL2: 'https://new.axilthemes.com/demo/template/etrade-rtl/assets/images/product/electric/product-05.png',
        stars: '(44)',
        title: '3D™ wireless headset',
        price: ['$49.99','$29.99'],
    },
    {
        id: 2,
        discount: 'Off 30%',
        imgURL1: 'https://new.axilthemes.com/demo/template/etrade-rtl/assets/images/product/electric/product-03.png',
        imgURL2: 'https://new.axilthemes.com/demo/template/etrade-rtl/assets/images/product/electric/product-03.png',
        stars: null,
        title: 'Logitech Streamcam',
        price: ['$49.99','$29.99'],
    },
    {
        id: 3,
        discount: null,
        imgURL1: 'https://new.axilthemes.com/demo/template/etrade-rtl/assets/images/product/electric/product-02.png',
        imgURL2: 'https://new.axilthemes.com/demo/template/etrade-rtl/assets/images/product/electric/product-06.png',
        stars: null,
        title: 'Level 20 RGB Cherry',
        price: ['$49.99','$29.99'],
    },
    {
        id: 4,
        discount: 'Off 20%',
        imgURL1: 'https://new.axilthemes.com/demo/template/etrade-rtl/assets/images/product/electric/product-01.png',
        imgURL2: 'https://new.axilthemes.com/demo/template/etrade-rtl/assets/images/product/electric/product-08.png',
        stars: '(64)',
        title: 'Yantiti Leather & Canvas Bags',
        price: ['$49.99','$29.99'],
    },
    {
        id: 5,
        discount: null,
        imgURL1: 'https://new.axilthemes.com/demo/template/etrade-rtl/assets/images/product/electric/product-08.png',
        imgURL2: 'https://new.axilthemes.com/demo/template/etrade-rtl/assets/images/product/electric/product-08.png',
        stars: null,
        title: '3D™ wireless headset',
        price: ['$49.99','$29.99'],
    },
    {
        id: 6,
        discount: 'Off 5%',
        imgURL1: 'https://new.axilthemes.com/demo/template/etrade-rtl/assets/images/product/electric/product-07.png',
        imgURL2: 'https://new.axilthemes.com/demo/template/etrade-rtl/assets/images/product/electric/product-08.png',
        stars: '(64)',
        title: 'Zone Headphone',
        price: ['$49.99','$29.99'],
    },
    {
        id: 7,
        discount: null,
        imgURL1: 'https://new.axilthemes.com/demo/template/etrade-rtl/assets/images/product/electric/product-06.png',
        imgURL2: 'https://new.axilthemes.com/demo/template/etrade-rtl/assets/images/product/electric/product-06.png',
        stars: null,
        title: 'Mice Logitech',
        price: ['$49.99','$29.99'],
    },
    {
        id: 8,
        discount: 'Off 15%',
        imgURL1: 'https://new.axilthemes.com/demo/template/etrade-rtl/assets/images/product/electric/product-05.png',
        imgURL2: 'https://new.axilthemes.com/demo/template/etrade-rtl/assets/images/product/electric/product-04.png',
        stars: null,
        title: 'Bass Meets Clarity',
        price: ['$49.99','$29.99'], 
    },
]

export default Data